apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-web-deployment
  labels:
    app: java-web
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: java-web
  template:
    metadata:
      labels:
        app: java-web
    spec:
      containers:
      - name: java-container
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}